name: tasker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
     # Architecture
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  get_it: ^7.6.0
  equatable: ^2.0.5
  
  # UI
  google_fonts: ^5.1.0
  table_calendar: ^3.0.9
  intl: ^0.18.1
  
  # Storage
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
